modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "wings"
version = "${file.jarVersion}"
displayName = "Wings"
authors = "Joy"
description = "The Wings mod introduces an assortment of avian and insectoid wings for all of your aerial travel needs."
logoFile = "logo.png"
[[dependencies.wings]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.wings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.1.21)"
ordering = "NONE"
side = "BOTH"
